export interface CatalogItem {
  id: string;
  name: string;
  collection: string;
  image: string;
  images: string[];
  specsImage?: string;
  style: string;
  recommendedFor: string[];
  description: string;
  glassesId?: string;
}

export interface CatalogCollection {
  id: string;
  title: string;
  badge: string;
  description: string;
  coverImage: string;
  images: string[];
  items: CatalogItem[];
}

export const CATALOG_COLLECTIONS: CatalogCollection[] = [
  {
    id: "cat-eye-edition",
    title: "Cat Eye Edition",
    badge: "Trending Collection",
    description: "Desain cat-eye ikonis yang memberikan kesan elegan, bold, dan menawan.",
    coverImage: "/katalog/Cat Eye Edition/1.webp",
    images: [
      "/katalog/Cat Eye Edition/1.webp",
      "/katalog/Cat Eye Edition/2.webp",
      "/katalog/Cat Eye Edition/Product Specs.webp",
    ],
    items: [
      {
        id: "cateye-1",
        name: "Cat Eye Signature — Gloss Black",
        collection: "Cat Eye Edition",
        image: "/katalog/Cat Eye Edition/1.webp",
        images: ["/katalog/Cat Eye Edition/1.webp", "/katalog/Cat Eye Edition/Product Specs.webp"],
        specsImage: "/katalog/Cat Eye Edition/Product Specs.webp",
        style: "Cat-Eye",
        recommendedFor: ["Heart", "Oval", "Round"],
        description: "Frame cat-eye elegan dengan sudut tegas dan finishing gloss premium.",
        glassesId: "cateye-frame",
      },
      {
        id: "cateye-2",
        name: "Cat Eye Velvet — Amber Tortoise",
        collection: "Cat Eye Edition",
        image: "/katalog/Cat Eye Edition/2.webp",
        images: ["/katalog/Cat Eye Edition/2.webp", "/katalog/Cat Eye Edition/Product Specs.webp"],
        specsImage: "/katalog/Cat Eye Edition/Product Specs.webp",
        style: "Cat-Eye",
        recommendedFor: ["Heart", "Oval", "Diamond"],
        description: "Warna tortoise eksklusif dengan gagang titanium yang sangat ringan.",
        glassesId: "cateye-frame",
      },
    ],
  },
  {
    id: "new-collection",
    title: "New Collection",
    badge: "Rilisan Terbaru",
    description: "Koleksi kacamata kekinian dengan material ringan dan anti-radiasi.",
    coverImage: "/katalog/New Collection/1.webp",
    images: [
      "/katalog/New Collection/1.webp",
      "/katalog/New Collection/2.webp",
      "/katalog/New Collection/Product Specs.webp",
    ],
    items: [
      {
        id: "new-1",
        name: "Metro Square Pro — Matte Black",
        collection: "New Collection",
        image: "/katalog/New Collection/1.webp",
        images: ["/katalog/New Collection/1.webp", "/katalog/New Collection/Product Specs.webp"],
        specsImage: "/katalog/New Collection/Product Specs.webp",
        style: "Square",
        recommendedFor: ["Round", "Oval", "Diamond"],
        description: "Desain persegi kontemporer dengan sudut halus, cocok untuk aktivitas harian.",
        glassesId: "square-frame",
      },
      {
        id: "new-2",
        name: "Aero Wire — Champagne Gold",
        collection: "New Collection",
        image: "/katalog/New Collection/2.webp",
        images: ["/katalog/New Collection/2.webp", "/katalog/New Collection/Product Specs.webp"],
        specsImage: "/katalog/New Collection/Product Specs.webp",
        style: "Round Wire",
        recommendedFor: ["Square", "Heart", "Diamond"],
        description: "Frame kawat bulat yang halus dan ringan, memberikan kesan retro modern.",
        glassesId: "oval-frame",
      },
    ],
  },
  {
    id: "titanium-edition",
    title: "Titanium Edition",
    badge: "Premium Series",
    description: "Koleksi titanium ultralight dengan ketahanan tinggi dan desain minimalis modern.",
    coverImage: "/katalog/Titanium Edition/1.webp",
    images: [
      "/katalog/Titanium Edition/1.webp",
      "/katalog/Titanium Edition/2.webp",
      "/katalog/Titanium Edition/Product Specs.webp",
    ],
    items: [
      {
        id: "titanium-1",
        name: "Titanium Pure — Matte Steel",
        collection: "Titanium Edition",
        image: "/katalog/Titanium Edition/1.webp",
        images: ["/katalog/Titanium Edition/1.webp", "/katalog/Titanium Edition/Product Specs.webp"],
        specsImage: "/katalog/Titanium Edition/Product Specs.webp",
        style: "Titanium",
        recommendedFor: ["Oval", "Square", "Heart"],
        description: "Frame titanium murni dengan bobot ultra ringan dan ketahanan luar biasa.",
        glassesId: "square-frame",
      },
      {
        id: "titanium-2",
        name: "Titanium Air — Gunmetal Gray",
        collection: "Titanium Edition",
        image: "/katalog/Titanium Edition/2.webp",
        images: ["/katalog/Titanium Edition/2.webp", "/katalog/Titanium Edition/Product Specs.webp"],
        specsImage: "/katalog/Titanium Edition/Product Specs.webp",
        style: "Titanium",
        recommendedFor: ["Oval", "Round", "Diamond"],
        description: "Gaya profesional yang tipis, presisi, dan sangat nyaman dipakai seharian.",
        glassesId: "oval-frame",
      },
    ],
  },
  {
    id: "metro-deek",
    title: "Metro Deek",
    badge: "Modern Urban",
    description: "Desain frame urban kontemporer dengan estetika clean dan material tangguh.",
    coverImage: "/katalog/Metro Deek/Feed 1.webp",
    images: [
      "/katalog/Metro Deek/Feed 1.webp",
      "/katalog/Metro Deek/Feed 2.webp",
      "/katalog/Metro Deek/Feed 3.webp",
    ],
    items: [
      {
        id: "metro-1",
        name: "Metro Deek Urban — Black Acetate",
        collection: "Metro Deek",
        image: "/katalog/Metro Deek/Feed 1.webp",
        images: ["/katalog/Metro Deek/Feed 1.webp"],
        style: "Urban Square",
        recommendedFor: ["Oval", "Round", "Heart"],
        description: "Frame tebal bergaya urban dengan siluet modern untuk penampilan bold.",
        glassesId: "square-frame",
      },
      {
        id: "metro-2",
        name: "Metro Deek Minimalist — Crystal Clear",
        collection: "Metro Deek",
        image: "/katalog/Metro Deek/Feed 2.webp",
        images: ["/katalog/Metro Deek/Feed 2.webp"],
        style: "Transparan",
        recommendedFor: ["Round", "Oval", "Square"],
        description: "Frame transparan bening dengan detail engsel yang kokoh dan estetik.",
        glassesId: "square-frame",
      },
      {
        id: "metro-3",
        name: "Metro Deek Executive — Deep Brown",
        collection: "Metro Deek",
        image: "/katalog/Metro Deek/Feed 3.webp",
        images: ["/katalog/Metro Deek/Feed 3.webp"],
        style: "Classic Square",
        recommendedFor: ["Oval", "Square", "Oblong"],
        description: "Sentuhan nuansa warna cokelat hangat untuk gaya profesional sehari-hari.",
        glassesId: "square-frame",
      },
    ],
  },
  {
    id: "quiet-luxury",
    title: "Quiet Luxury",
    badge: "Sophisticated Series",
    description: "Frame mewah nan understated dengan detail halus dan kenyamanan maksimal.",
    coverImage: "/katalog/Quiet Luxury/CATALOG NEW-01.webp",
    images: [
      "/katalog/Quiet Luxury/CATALOG NEW-01.webp",
      "/katalog/Quiet Luxury/CATALOG NEW-02.webp",
      "/katalog/Quiet Luxury/Detail Spec.webp",
    ],
    items: [
      {
        id: "luxury-1",
        name: "Quiet Luxury One — Subtle Gold Rim",
        collection: "Quiet Luxury",
        image: "/katalog/Quiet Luxury/CATALOG NEW-01.webp",
        images: ["/katalog/Quiet Luxury/CATALOG NEW-01.webp", "/katalog/Quiet Luxury/Detail Spec.webp"],
        specsImage: "/katalog/Quiet Luxury/Detail Spec.webp",
        style: "Luxury Oval",
        recommendedFor: ["Square", "Oval", "Heart"],
        description: "Keanggunan minimalis dengan aksen emas halus yang sangat berkelas.",
        glassesId: "oval-frame",
      },
      {
        id: "luxury-2",
        name: "Quiet Luxury Two — Matte Platinum",
        collection: "Quiet Luxury",
        image: "/katalog/Quiet Luxury/CATALOG NEW-02.webp",
        images: ["/katalog/Quiet Luxury/CATALOG NEW-02.webp", "/katalog/Quiet Luxury/Detail Spec.webp"],
        specsImage: "/katalog/Quiet Luxury/Detail Spec.webp",
        style: "Luxury Round",
        recommendedFor: ["Square", "Oblong", "Diamond"],
        description: "Finishing platinum matte ultralight untuk kenyamanan dan gengsi ekstra.",
        glassesId: "round-frame",
      },
    ],
  },
  {
    id: "shades-of-elegance",
    title: "Shades Of Elegance",
    badge: "Elegance Collection",
    description: "Sentuhan siluet elegan dengan gradasi warna menawan untuk penampilan anggun.",
    coverImage: "/katalog/Shades Of Elegance/1.webp",
    images: [
      "/katalog/Shades Of Elegance/1.webp",
      "/katalog/Shades Of Elegance/2.webp",
      "/katalog/Shades Of Elegance/Product Specs.webp",
    ],
    items: [
      {
        id: "elegance-1",
        name: "Shades Of Elegance Alpha — Soft Rose Gold",
        collection: "Shades Of Elegance",
        image: "/katalog/Shades Of Elegance/1.webp",
        images: ["/katalog/Shades Of Elegance/1.webp", "/katalog/Shades Of Elegance/Product Specs.webp"],
        specsImage: "/katalog/Shades Of Elegance/Product Specs.webp",
        style: "Cat-Eye Elegance",
        recommendedFor: ["Heart", "Oval", "Round"],
        description: "Frame anggun dengan lengkungan halus, menonjolkan fitur estetis wajah.",
        glassesId: "cateye-frame",
      },
      {
        id: "elegance-2",
        name: "Shades Of Elegance Beta — Midnight Crystal",
        collection: "Shades Of Elegance",
        image: "/katalog/Shades Of Elegance/2.webp",
        images: ["/katalog/Shades Of Elegance/2.webp", "/katalog/Shades Of Elegance/Product Specs.webp"],
        specsImage: "/katalog/Shades Of Elegance/Product Specs.webp",
        style: "Soft Square",
        recommendedFor: ["Round", "Oval", "Diamond"],
        description: "Kombinasi warna kristal gelap dengan kilau mewah yang menonjolkan percaya diri.",
        glassesId: "square-frame",
      },
    ],
  },
  {
    id: "shades-edition",
    title: "Shades Edition",
    badge: "Sunglasses Series",
    description: "Koleksi kacamata hitam (sunglasses) bergaya modern dengan proteksi UV400 maksimal.",
    coverImage: "/katalog/Shades Edition/1.webp",
    images: [
      "/katalog/Shades Edition/1.webp",
      "/katalog/Shades Edition/3.webp",
      "/katalog/Shades Edition/Product Specs.webp",
    ],
    items: [
      {
        id: "shades-1",
        name: "Shades Edition Classic — Dark Smoke",
        collection: "Shades Edition",
        image: "/katalog/Shades Edition/1.webp",
        images: ["/katalog/Shades Edition/1.webp", "/katalog/Shades Edition/Product Specs.webp"],
        specsImage: "/katalog/Shades Edition/Product Specs.webp",
        style: "Sunglasses Square",
        recommendedFor: ["Oval", "Round", "Heart"],
        description: "Kacamata hitam gaya klasik dengan lensa dark smoke anti-glare & proteksi UV400 maksimal.",
        glassesId: "sunglasses-black",
      },
      {
        id: "shades-2",
        name: "Shades Edition Modern — Amber Gold",
        collection: "Shades Edition",
        image: "/katalog/Shades Edition/3.webp",
        images: ["/katalog/Shades Edition/3.webp", "/katalog/Shades Edition/Product Specs.webp"],
        specsImage: "/katalog/Shades Edition/Product Specs.webp",
        style: "Sunglasses Aviator",
        recommendedFor: ["Square", "Oval", "Diamond"],
        description: "Siluet modern dengan aksen warna amber gold yang elegan untuk penampilan outdoor stylish.",
        glassesId: "sunglasses-square-metal",
      },
    ],
  },
  {
    id: "the-feline-silhouette",
    title: "The Feline Silhouette",
    badge: "Cat-Eye Luxury",
    description: "Siluet cat-eye ikonis nan feminin dengan lekukan tajam yang mempertegas karakter dan pesona tatapan mata.",
    coverImage: "/katalog/The Feline Silhouette/5.png",
    images: [
      "/katalog/The Feline Silhouette/5.png",
      "/katalog/The Feline Silhouette/6.png",
      "/katalog/The Feline Silhouette/7.png",
      "/katalog/The Feline Silhouette/8.png",
    ],
    items: [
      {
        id: "feline-1",
        name: "The Feline Silhouette 01 — Onyx Black",
        collection: "The Feline Silhouette",
        image: "/katalog/The Feline Silhouette/5.png",
        images: ["/katalog/The Feline Silhouette/5.png"],
        style: "Cat-Eye Luxury",
        recommendedFor: ["Heart", "Oval", "Round"],
        description: "Siluet cat-eye bold dengan warna hitam pekat elegan yang memikat dan penuh percaya diri.",
        glassesId: "cateye-frame",
      },
      {
        id: "feline-2",
        name: "The Feline Silhouette 02 — Tortoise Luxe",
        collection: "The Feline Silhouette",
        image: "/katalog/The Feline Silhouette/6.png",
        images: ["/katalog/The Feline Silhouette/6.png"],
        style: "Cat-Eye Statement",
        recommendedFor: ["Oval", "Diamond", "Heart"],
        description: "Aksen motif tortoise hangat berpadu dengan sudut cat-eye yang tajam dan dinamis.",
        glassesId: "cateye-frame",
      },
      {
        id: "feline-3",
        name: "The Feline Silhouette 03 — Crimson Haze",
        collection: "The Feline Silhouette",
        image: "/katalog/The Feline Silhouette/7.png",
        images: ["/katalog/The Feline Silhouette/7.png"],
        style: "Cat-Eye Modern",
        recommendedFor: ["Round", "Oval", "Heart"],
        description: "Nuansa crimson modern dengan kilau mewah yang memberikan sentuhan visual mempesona.",
        glassesId: "cateye-frame",
      },
      {
        id: "feline-4",
        name: "The Feline Silhouette 04 — Amber Glow",
        collection: "The Feline Silhouette",
        image: "/katalog/The Feline Silhouette/8.png",
        images: ["/katalog/The Feline Silhouette/8.png"],
        style: "Cat-Eye Minimalist",
        recommendedFor: ["Heart", "Diamond", "Oval"],
        description: "Gradasi amber natural yang ringan, harmonis, dan sangat anggun untuk pemakaian harian.",
        glassesId: "cateye-frame",
      },
    ],
  },
  {
    id: "the-lucid-vision",
    title: "The Lucid Vision",
    badge: "Crystal Clarity",
    description: "Frame transparan ultra-clear dengan estetika futuristik dan modern yang memberi kesan jernih, ringan, dan elegan.",
    coverImage: "/katalog/The Lucid Vision/14.png",
    images: [
      "/katalog/The Lucid Vision/14.png",
      "/katalog/The Lucid Vision/15.png",
      "/katalog/The Lucid Vision/16.png",
    ],
    items: [
      {
        id: "lucid-1",
        name: "The Lucid Vision 01 — Pure Crystal",
        collection: "The Lucid Vision",
        image: "/katalog/The Lucid Vision/14.png",
        images: ["/katalog/The Lucid Vision/14.png"],
        style: "Transparent Clear",
        recommendedFor: ["Oval", "Round", "Square"],
        description: "Material transparan murni berkilau tinggi yang memberikan kesan wajah lebih cerah dan bersih.",
        glassesId: "square-frame",
      },
      {
        id: "lucid-2",
        name: "The Lucid Vision 02 — Smoked Glass",
        collection: "The Lucid Vision",
        image: "/katalog/The Lucid Vision/15.png",
        images: ["/katalog/The Lucid Vision/15.png"],
        style: "Smoked Crystal",
        recommendedFor: ["Square", "Oblong", "Diamond"],
        description: "Transparansi abu-abu halus dengan sentuhan industrial yang sophisticated.",
        glassesId: "square-frame",
      },
      {
        id: "lucid-3",
        name: "The Lucid Vision 03 — Champagne Hue",
        collection: "The Lucid Vision",
        image: "/katalog/The Lucid Vision/16.png",
        images: ["/katalog/The Lucid Vision/16.png"],
        style: "Warm Crystal",
        recommendedFor: ["Oval", "Heart", "Diamond"],
        description: "Nuansa champagne lembut dengan kejernihan optik premium untuk penampilan berkelas.",
        glassesId: "square-frame",
      },
    ],
  },
  {
    id: "the-skena-gaze",
    title: "The Skena Gaze",
    badge: "Bold Skena Edition",
    description: "Koleksi statement frame berani dengan profil tegas, berjiwa muda, dan estetik kekinian untuk tampilan skena yang memukau.",
    coverImage: "/katalog/The Skena Gaze/9.png",
    images: [
      "/katalog/The Skena Gaze/9.png",
      "/katalog/The Skena Gaze/10.png",
      "/katalog/The Skena Gaze/11.png",
      "/katalog/The Skena Gaze/12.png",
      "/katalog/The Skena Gaze/13.png",
    ],
    items: [
      {
        id: "skena-1",
        name: "The Skena Gaze 01 — Bold Noir",
        collection: "The Skena Gaze",
        image: "/katalog/The Skena Gaze/9.png",
        images: ["/katalog/The Skena Gaze/9.png"],
        style: "Chunky Square",
        recommendedFor: ["Round", "Oval", "Heart"],
        description: "Siluet chunky persegi tebal bergaya skena modern yang langsung menarik perhatian.",
        glassesId: "square-frame",
      },
      {
        id: "skena-2",
        name: "The Skena Gaze 02 — Forest Edge",
        collection: "The Skena Gaze",
        image: "/katalog/The Skena Gaze/10.png",
        images: ["/katalog/The Skena Gaze/10.png"],
        style: "Geometric Bold",
        recommendedFor: ["Oval", "Square", "Diamond"],
        description: "Desain geometris tajam dengan warna hijau lumut gelap yang berkarakter kuat.",
        glassesId: "square-frame",
      },
      {
        id: "skena-3",
        name: "The Skena Gaze 03 — Retro Havana",
        collection: "The Skena Gaze",
        image: "/katalog/The Skena Gaze/11.png",
        images: ["/katalog/The Skena Gaze/11.png"],
        style: "Vintage Skena",
        recommendedFor: ["Square", "Oblong", "Oval"],
        description: "Sentuhan retro havana vintage dengan bridge proporsional untuk kenyamanan optimal.",
        glassesId: "square-frame",
      },
      {
        id: "skena-4",
        name: "The Skena Gaze 04 — Modern Slate",
        collection: "The Skena Gaze",
        image: "/katalog/The Skena Gaze/12.png",
        images: ["/katalog/The Skena Gaze/12.png"],
        style: "Architectural Square",
        recommendedFor: ["Round", "Diamond", "Heart"],
        description: "Garis arsitektural tegas dengan warna abu batu modern yang bersih dan berwibawa.",
        glassesId: "square-frame",
      },
      {
        id: "skena-5",
        name: "The Skena Gaze 05 — Deep Amber",
        collection: "The Skena Gaze",
        image: "/katalog/The Skena Gaze/13.png",
        images: ["/katalog/The Skena Gaze/13.png"],
        style: "Statement Acetate",
        recommendedFor: ["Oval", "Heart", "Square"],
        description: "Warna madu amber pekat dengan kilau material asetat premium yang sangat mewah.",
        glassesId: "square-frame",
      },
    ],
  },
];
