// lib/softlens.ts
import { KONSULTASI_WA_NUMBER } from "./branches";

/** Nomor WA CS Softlens disamakan dengan Nomor WA Konsultasi Optik I See You */
export const SOFTLENS_CS_NUMBER = KONSULTASI_WA_NUMBER; // "62895415614261"

export const SOFTLENS_CS_WA_URL = (productName?: string) => {
  const msg = productName
    ? `Halo CS Optik I See You 👋, saya tertarik dengan produk "${productName}" di Katalog Soflens. Boleh info stok, ukuran minus/silinder, dan cara pemesanan?`
    : `Halo CS Optik I See You 👋, saya mau bertanya mengenai koleksi Softlens & Aksesoris perawatan mata.`;
  return `https://wa.me/${SOFTLENS_CS_NUMBER}?text=${encodeURIComponent(msg)}`;
};

export interface SoftlensProduct {
  id: string;
  name: string;
  category: "Koleksi Premium" | "Aksesoris & Perawatan";
  colorFamily: "brown" | "grey" | "hazel" | "natural" | "colorful" | "accessory";
  specs: string[];
  description: string;
  price: number;
  priceFormatted: string;
  originalPrice?: number;
  originalPriceFormatted?: string;
  discountPercentage?: string;
  image: string;
  hoverImage?: string;
  detailPoster?: string;
  volume?: string;
  diameter?: string;
  waterContent?: string;
  usageDuration?: string;
  isAccessory?: boolean;
  badgeText?: string;
}

export interface CartItem {
  product: SoftlensProduct;
  quantity: number;
}

export const SOFTLENS_SPECS = [
  "Anti Blue Light",
  "Smooth Surface",
  "All Day Comfort",
  "For Sensitive Eyes",
  "UV Protection",
];

export const SOFTLENS_CATEGORIES = [
  { id: "all", label: "Semua Produk (21)" },
  { id: "Koleksi Premium", label: "Koleksi Premium Softlens" },
  { id: "Aksesoris & Perawatan", label: "Aksesoris & Perawatan" },
];

export const COLOR_FILTERS = [
  { id: "all", label: "Semua Warna" },
  { id: "brown", label: "Cokelat (Brown)" },
  { id: "grey", label: "Abu-Abu (Grey)" },
  { id: "hazel", label: "Hazel & Emas" },
  { id: "natural", label: "Natural & Bening" },
  { id: "colorful", label: "Warna Anti Blue Light" },
  { id: "accessory", label: "Cairan & Perawatan" },
];

export const SOFTLENS_PRODUCTS: SoftlensProduct[] = [
  // ── KOLEKSI PREMIUM SOFTLENS (13 PRODUK ASLI EDITED PNG + DETAIL POSTER) ─────
  {
    id: "ice-no5-brown",
    name: "Exoticon ICE N°5 — Brown",
    category: "Koleksi Premium",
    colorFamily: "brown",
    specs: ["Exoticon Series", "High Oxygen", "All Day Comfort", "UV Protection"],
    description: "Softlens Exoticon ICE N°5 varian Brown dengan tone cokelat hangat berkilau nan memikat.",
    price: 55000,
    priceFormatted: "Rp 55.000",
    originalPrice: 70000,
    originalPriceFormatted: "Rp 70.000",
    discountPercentage: "21% OFF",
    image: "/Katalog Soflens/Assets Soflens/Exoticon ice-no5-brown.webp",
    hoverImage: "/Katalog Soflens/Assets detail produk soflens/Exoticon N5.webp",
    detailPoster: "/Katalog Soflens/Assets detail produk soflens/Exoticon N5.webp",
    diameter: "14.5 mm",
    waterContent: "42%",
    usageDuration: "6 Bulan",
    badgeText: "Best Seller Exoticon",
  },
  {
    id: "ice-no5-grey",
    name: "Exoticon ICE N°5 — Grey",
    category: "Koleksi Premium",
    colorFamily: "grey",
    specs: ["Exoticon Series", "Crystal Glow", "Smooth Surface", "UV Protection"],
    description: "Softlens Exoticon ICE N°5 varian Grey dengan sentuhan abu-abu kristal nan anggun dan mempesona.",
    price: 55000,
    priceFormatted: "Rp 55.000",
    originalPrice: 70000,
    originalPriceFormatted: "Rp 70.000",
    discountPercentage: "21% OFF",
    image: "/Katalog Soflens/Assets Soflens/Exoticon ice-no5-grey.webp",
    hoverImage: "/Katalog Soflens/Assets detail produk soflens/Exoticon Ice no5-Grey-Detail.webp",
    detailPoster: "/Katalog Soflens/Assets detail produk soflens/Exoticon Ice no5-Grey-Detail.webp",
    diameter: "14.5 mm",
    waterContent: "42%",
    usageDuration: "6 Bulan",
    badgeText: "Exoticon Series",
  },
  {
    id: "ice-no5-black",
    name: "Exoticon ICE N°5 — Black",
    category: "Koleksi Premium",
    colorFamily: "natural",
    specs: ["Exoticon Series", "Deep Eye Effect", "All Day Comfort", "UV Protection"],
    description: "Softlens Exoticon ICE N°5 varian Black memberikan efek mata lebih tegas, besar, dan tetap alami.",
    price: 55000,
    priceFormatted: "Rp 55.000",
    originalPrice: 70000,
    originalPriceFormatted: "Rp 70.000",
    discountPercentage: "21% OFF",
    image: "/Katalog Soflens/Assets Soflens/Ice no5-Black.webp",
    hoverImage: "/Katalog Soflens/Assets detail produk soflens/Exoticon N5.webp",
    detailPoster: "/Katalog Soflens/Assets detail produk soflens/Exoticon N5.webp",
    diameter: "14.5 mm",
    waterContent: "42%",
    usageDuration: "6 Bulan",
    badgeText: "Exoticon Series",
  },
  {
    id: "miss-ice-selena-grey",
    name: "Exoticon Miss ICE — Selena Grey",
    category: "Koleksi Premium",
    colorFamily: "grey",
    specs: ["Miss ICE Series", "K-Beauty Velvet", "Ultra Soft Lens", "UV Protection"],
    description: "Varian eksklusif Exoticon Miss ICE Selena Grey dengan warna abu-abu elegan nan manis gaya K-Beauty.",
    price: 55000,
    priceFormatted: "Rp 55.000",
    originalPrice: 75000,
    originalPriceFormatted: "Rp 75.000",
    discountPercentage: "27% OFF",
    image: "/Katalog Soflens/Assets Soflens/Exoticon Miss Ice-Selena Grey.webp",
    hoverImage: "/Katalog Soflens/Assets detail produk soflens/Exoticon Miss Ice.webp",
    detailPoster: "/Katalog Soflens/Assets detail produk soflens/Exoticon Miss Ice.webp",
    diameter: "14.5 mm",
    waterContent: "42%",
    usageDuration: "6 Bulan",
    badgeText: "Miss ICE Series",
  },
  {
    id: "exo-clear",
    name: "Exoticon EXO CLEAR",
    category: "Koleksi Premium",
    colorFamily: "natural",
    specs: ["Monthly Disposable", "Super Thin Vision", "For Sensitive Eyes", "Etafilcon A"],
    description: "Softlens bening bulanan ultrathin Etafilcon A, memberikan penglihatan super tajam & sangat nyaman.",
    price: 45000,
    priceFormatted: "Rp 45.000",
    originalPrice: 60000,
    originalPriceFormatted: "Rp 60.000",
    discountPercentage: "25% OFF",
    image: "/Katalog Soflens/Assets Soflens/exoticon-exo clear.webp",
    hoverImage: "/Katalog Soflens/Assets detail produk soflens/Exoticon Exo Clear.webp",
    detailPoster: "/Katalog Soflens/Assets detail produk soflens/Exoticon Exo Clear.webp",
    diameter: "14.2 mm",
    waterContent: "55%",
    usageDuration: "1 Bulan",
    badgeText: "Lensa Bening",
  },
  {
    id: "golden-eye-prestige",
    name: "Golden Eye Prestige",
    category: "Koleksi Premium",
    colorFamily: "hazel",
    specs: ["Prestige Color", "High Moisture", "All Day Comfort", "Golden Glow"],
    description: "Warna hazel emas berkelas ala Golden Eye Prestige untuk efek kilau mata mewah dan penuh pesona.",
    price: 35000,
    priceFormatted: "Rp 35.000",
    originalPrice: 50000,
    originalPriceFormatted: "Rp 50.000",
    discountPercentage: "30% OFF",
    image: "/Katalog Soflens/Assets Soflens/Golden Eye Prestige.webp",
    hoverImage: "/Katalog Soflens/Assets detail produk soflens/Golden Eye Prestige.webp",
    detailPoster: "/Katalog Soflens/Assets detail produk soflens/Golden Eye Prestige.webp",
    diameter: "14.5 mm",
    waterContent: "45%",
    usageDuration: "6 Bulan",
    badgeText: "Prestige Series",
  },
  {
    id: "new-more-dubai",
    name: "New More Dubai",
    category: "Koleksi Premium",
    colorFamily: "hazel",
    specs: ["Exotic Dubai", "Rich Pigment", "Smooth Surface", "All Day Comfort"],
    description: "Sentuhan warna eksotis ala Timur Tengah yang mewah, memberikan gradasi mata cantik dan dramatis.",
    price: 35000,
    priceFormatted: "Rp 35.000",
    originalPrice: 50000,
    originalPriceFormatted: "Rp 50.000",
    discountPercentage: "30% OFF",
    image: "/Katalog Soflens/Assets Soflens/New More Dubai.webp",
    hoverImage: "/Katalog Soflens/Assets detail produk soflens/New More Dubai.webp",
    detailPoster: "/Katalog Soflens/Assets detail produk soflens/New More Dubai.webp",
    diameter: "14.5 mm",
    waterContent: "45%",
    usageDuration: "6 Bulan",
    badgeText: "Dubai Series",
  },
  {
    id: "miracle",
    name: "Living Color Miracle",
    category: "Koleksi Premium",
    colorFamily: "brown",
    specs: ["Exotic Glow", "Living Color", "Smooth Surface", "UV Protection"],
    description: "Sentuhan warna cokelat eksotis dengan gradasi warna hidup yang memberikan kilau natural.",
    price: 35000,
    priceFormatted: "Rp 35.000",
    originalPrice: 50000,
    originalPriceFormatted: "Rp 50.000",
    discountPercentage: "30% OFF",
    image: "/Katalog Soflens/Assets Soflens/Miracle.webp",
    hoverImage: "/Katalog Soflens/Assets detail produk soflens/Miracle-Edit.webp",
    detailPoster: "/Katalog Soflens/Assets detail produk soflens/Miracle-Edit.webp",
    diameter: "14.2 mm",
    waterContent: "45%",
    usageDuration: "6 Bulan",
    badgeText: "Living Color",
  },
  {
    id: "moxie",
    name: "Exoticon Moxie",
    category: "Koleksi Premium",
    colorFamily: "brown",
    specs: ["Exoticon Series", "Modern Style", "Smooth Surface", "All Day Comfort"],
    description: "Warna cokelat kontemporer kemasan Exoticon Moxie untuk gaya hidup aktif dan modis.",
    price: 35000,
    priceFormatted: "Rp 35.000",
    originalPrice: 50000,
    originalPriceFormatted: "Rp 50.000",
    discountPercentage: "30% OFF",
    image: "/Katalog Soflens/Assets Soflens/moxie.webp",
    hoverImage: "/Katalog Soflens/Assets detail produk soflens/Exoticon-Moxie-Detail.webp",
    detailPoster: "/Katalog Soflens/Assets detail produk soflens/Exoticon-Moxie-Detail.webp",
    diameter: "14.2 mm",
    waterContent: "45%",
    usageDuration: "6 Bulan",
    badgeText: "Exoticon Moxie",
  },
  {
    id: "pure-color-comfort",
    name: "Pure Color Comfort",
    category: "Koleksi Premium",
    colorFamily: "natural",
    specs: ["High Moisture", "For Sensitive Eyes", "Smooth Surface", "All Day Comfort"],
    description: "Desain warna lembut berteknologi High-Moisture yang sangat ramah untuk mata sensitif.",
    price: 35000,
    priceFormatted: "Rp 35.000",
    originalPrice: 50000,
    originalPriceFormatted: "Rp 50.000",
    discountPercentage: "30% OFF",
    image: "/Katalog Soflens/Assets Soflens/Pure Color Comfort.webp",
    hoverImage: "/Katalog Soflens/Assets detail produk soflens/Pure Color Comfort.webp",
    detailPoster: "/Katalog Soflens/Assets detail produk soflens/Pure Color Comfort.webp",
    diameter: "14.2 mm",
    waterContent: "48%",
    usageDuration: "6 Bulan",
    badgeText: "Comfort Series",
  },
  {
    id: "russian-velvet-irina-grey",
    name: "Russian Velvet — Irina Grey",
    category: "Koleksi Premium",
    colorFamily: "grey",
    specs: ["No Limbal Ring", "K-Beauty Velvet", "All Day Comfort", "Soft Grey"],
    description: "Gaya beludru mewah ala K-Beauty tanpa garis tepi (no limbal ring) dengan warna Irina Grey.",
    price: 35000,
    priceFormatted: "Rp 35.000",
    originalPrice: 55000,
    originalPriceFormatted: "Rp 55.000",
    discountPercentage: "36% OFF",
    image: "/Katalog Soflens/Assets Soflens/Rusian-velvet-Irina Grey.webp",
    hoverImage: "/Katalog Soflens/Assets detail produk soflens/Rusian Velvet - Edited.webp",
    detailPoster: "/Katalog Soflens/Assets detail produk soflens/Rusian Velvet - Edited.webp",
    diameter: "14.0 mm",
    waterContent: "45%",
    usageDuration: "6 Bulan",
    badgeText: "K-Idol Favorite",
  },
  {
    id: "russian-velvet-sofiya-dark-glow",
    name: "Russian Velvet — Sofiya Dark Glow",
    category: "Koleksi Premium",
    colorFamily: "grey",
    specs: ["No Limbal Ring", "Dark Glow Effect", "K-Beauty Velvet", "All Day Comfort"],
    description: "Russian Velvet tone Sofiya Dark Glow dengan efek gradasi gelap nan dramatis dan memikat.",
    price: 35000,
    priceFormatted: "Rp 35.000",
    originalPrice: 55000,
    originalPriceFormatted: "Rp 55.000",
    discountPercentage: "36% OFF",
    image: "/Katalog Soflens/Assets Soflens/Rusian-velvet-Sofiya Dark Glow.webp",
    hoverImage: "/Katalog Soflens/Assets detail produk soflens/Rusian Velvet - Edited.webp",
    detailPoster: "/Katalog Soflens/Assets detail produk soflens/Rusian Velvet - Edited.webp",
    diameter: "14.0 mm",
    waterContent: "45%",
    usageDuration: "6 Bulan",
    badgeText: "Dark Glow Series",
  },
  {
    id: "twilight",
    name: "Color Twilight",
    category: "Koleksi Premium",
    colorFamily: "colorful",
    specs: ["Anti Blue Light", "Phosphorylcholine PC", "Smooth Surface", "Eye Protection"],
    description: "Teknologi Anti Blue Light dengan bahan Phosphorylcholine (PC) murni untuk perlindungan gadget.",
    price: 35000,
    priceFormatted: "Rp 35.000",
    originalPrice: 50000,
    originalPriceFormatted: "Rp 50.000",
    discountPercentage: "30% OFF",
    image: "/Katalog Soflens/Assets Soflens/Twilight.webp",
    hoverImage: "/Katalog Soflens/Assets detail produk soflens/Twilight-Katalog.webp",
    detailPoster: "/Katalog Soflens/Assets detail produk soflens/Twilight-Katalog.webp",
    diameter: "14.2 mm",
    waterContent: "48%",
    usageDuration: "6 Bulan",
    badgeText: "Anti Blue Light",
  },

    // ── AKSESORIS & PERAWATAN SOFLENS & KACAMATA (15 PRODUK HIENIS) ──────────────
  {
    id: "ice-150ml",
    name: "ICE Solution (150ML)",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Pro-Vitamin B5", "Multi-Purpose", "All-In-One Sterile", "Botol Besar"],
    description: "Cairan pembersih dan perendam softlens ICE botol besar 150ml dengan kandungan Pro-Vitamin B5.",
    price: 30000,
    priceFormatted: "Rp 30.000",
    originalPrice: 40000,
    originalPriceFormatted: "Rp 40.000",
    discountPercentage: "25% OFF",
    image: "/Katalog Soflens/Aksesoris/Cairan Soflens Ice-150ml.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Cairan Soflens Ice-150ml.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Cairan Soflens Ice-150ml.webp",
    volume: "150ML",
    isAccessory: true,
    badgeText: "Cairan 150ML",
  },
  {
    id: "ice-60ml",
    name: "ICE Solution (60ML)",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Pro-Vitamin B5", "Travel Friendly", "Sterile Solution", "Kemasan Praktis"],
    description: "Cairan pembersih softlens ICE ukuran praktis 60ml. Travel friendly & mudah dibawa bepergian.",
    price: 20000,
    priceFormatted: "Rp 20.000",
    originalPrice: 28000,
    originalPriceFormatted: "Rp 28.000",
    discountPercentage: "28% OFF",
    image: "/Katalog Soflens/Aksesoris/cairan soflens ice-60ml.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/cairan soflens ice-60ml.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/cairan soflens ice-60ml.webp",
    volume: "60ML",
    isAccessory: true,
    badgeText: "Cairan 60ML",
  },
  {
    id: "x2-120ml",
    name: "X2 Solution (120ML)",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Advanced Formula", "Extra Delicate Care", "MUI Halal Certified", "120ML"],
    description: "Cairan pembersih softlens X2 120ml dengan sertifikasi Halal MUI untuk higienitas ekstra.",
    price: 30000,
    priceFormatted: "Rp 30.000",
    originalPrice: 40000,
    originalPriceFormatted: "Rp 40.000",
    discountPercentage: "25% OFF",
    image: "/Katalog Soflens/Aksesoris/Cairan Soflens X2.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Cairan Soflens X2.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Cairan Soflens X2.webp",
    volume: "120ML",
    isAccessory: true,
    badgeText: "Halal MUI",
  },
  {
    id: "x2-60ml",
    name: "X2 Solution (60ML)",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Advanced Formula", "Travel Size 60ML", "MUI Halal Certified", "Steril & Lembut"],
    description: "Cairan pembersih softlens X2 kemasan praktis 60ml, mudah dibawa ke mana saja & menjaga kelembaban lensa.",
    price: 20000,
    priceFormatted: "Rp 20.000",
    originalPrice: 28000,
    originalPriceFormatted: "Rp 28.000",
    discountPercentage: "28% OFF",
    image: "/Katalog Soflens/Aksesoris/Cairan Soflens X2.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Cairan Soflens X2.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Cairan Soflens X2.webp",
    volume: "60ML",
    isAccessory: true,
    badgeText: "Travel 60ML",
  },
  {
    id: "x2-contacts-15ml",
    name: "X2 Contacts Tetes Mata (15ML)",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Eye Drops 15ml", "Anti-Dryness", "Instant Refresh", "Khusus Soflens"],
    description: "Tetes mata khusus pengguna softlens X2 Contacts 15ml meredakan mata kering di ruangan AC.",
    price: 25000,
    priceFormatted: "Rp 25.000",
    originalPrice: 35000,
    originalPriceFormatted: "Rp 35.000",
    discountPercentage: "28% OFF",
    image: "/Katalog Soflens/Aksesoris/X2 Contacts.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/X2 Contacts.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/X2 Contacts.webp",
    volume: "15ML",
    isAccessory: true,
    badgeText: "Tetes Mata",
  },
  {
    id: "pure-n-soft-60ml",
    name: "Pure N'Soft Solution (60ML)",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Hyaluronic Gentle", "Ekonomis & Steril", "Lepas Endapan Protein", "Kemasan 60ML"],
    description: "Cairan pembersih & perendam softlens Pure N'Soft 60ml menjaga lensa tetap higienis dan nyaman dipakai seharian.",
    price: 8000,
    priceFormatted: "Rp 8.000",
    originalPrice: 12000,
    originalPriceFormatted: "Rp 12.000",
    discountPercentage: "33% OFF",
    image: "/Katalog Soflens/Aksesoris/Cairan Soflens  Men Soft.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Cairan Soflens  Men Soft.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Cairan Soflens  Men Soft.webp",
    volume: "60ML",
    isAccessory: true,
    badgeText: "Hemat & Steril",
  },
  {
    id: "case-magnet-coklat",
    name: "Case Magnet Exclusive (Coklat)",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Magnetic Closure", "Hard Case Protection", "Luxury Finish", "Beludru Dalam"],
    description: "Wadah penyimpanan kacamata & softlens hardcase magnet motif coklat mewah dengan interior beludru lembut.",
    price: 35000,
    priceFormatted: "Rp 35.000",
    originalPrice: 50000,
    originalPriceFormatted: "Rp 50.000",
    discountPercentage: "30% OFF",
    image: "/Katalog Soflens/Aksesoris/Case Magnet Coklat.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Case Magnet Coklat.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Case Magnet Coklat.webp",
    isAccessory: true,
    badgeText: "Exclusive Case",
  },
  {
    id: "case-magnet-pastel",
    name: "Case Magnet Premium (Pastel)",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Magnetic Lock", "Lightweight Hardcase", "Soft Velvet Interior", "Anti-Gores"],
    description: "Kotak kacamata & softlens bermagnet edisi pastel ringkas & kokoh melindungi dari benturan.",
    price: 30000,
    priceFormatted: "Rp 30.000",
    originalPrice: 45000,
    originalPriceFormatted: "Rp 45.000",
    discountPercentage: "33% OFF",
    image: "/Katalog Soflens/Aksesoris/Case Magnet.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Case Magnet.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Case Magnet.webp",
    isAccessory: true,
    badgeText: "Magnet Lock",
  },
  {
    id: "cleaner-lensa-nex",
    name: "Cleaner Lensa NEX Anti-Fog (30ML)",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Anti-Fog Spray", "High Definition Clean", "Streak-Free", "Aman untuk Coating"],
    description: "Cairan pembersih lensa kacamata NEX anti-embun & anti-static, membuat pandangan tetap jernih HD.",
    price: 20000,
    priceFormatted: "Rp 20.000",
    originalPrice: 30000,
    originalPriceFormatted: "Rp 30.000",
    discountPercentage: "33% OFF",
    image: "/Katalog Soflens/Aksesoris/Cleaner Lensa Nex.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Cleaner Lensa Nex.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Cleaner Lensa Nex.webp",
    volume: "30ML",
    isAccessory: true,
    badgeText: "Anti-Fog Spray",
  },
  {
    id: "cleaner-biasa",
    name: "Spray Cleaner Lensa Standard (30ML)",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Sanitizer Spray", "Pocket Size", "Debu & Minyak Hilang", "Jernih Maksimal"],
    description: "Pembersih semprot kacamata & wadah softlens efektif mengangkat noda minyak dan debu seketika.",
    price: 10000,
    priceFormatted: "Rp 10.000",
    originalPrice: 15000,
    originalPriceFormatted: "Rp 15.000",
    discountPercentage: "33% OFF",
    image: "/Katalog Soflens/Aksesoris/Cleaner Biasa.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Cleaner Biasa.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Cleaner Biasa.webp",
    volume: "30ML",
    isAccessory: true,
    badgeText: "Pembersih Lensa",
  },
  {
    id: "mesin-pencuci-soflens",
    name: "Mesin Pencuci Softlens (Ultrasonic)",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Vibrasi Otomatis", "USB Rechargeable", "Pembersih Kuman Deep Clean", "Steril 3 Menit"],
    description: "Mesin pembersih getar otomatis ultrasonic membuang kotoran & endapan protein pada softlens tanpa merusak serat.",
    price: 15000,
    priceFormatted: "Rp 15.000",
    originalPrice: 25000,
    originalPriceFormatted: "Rp 25.000",
    discountPercentage: "40% OFF",
    image: "/Katalog Soflens/Aksesoris/Mesin Pencuci Soflens.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Mesin Pencuci Soflens.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Mesin Pencuci Soflens.webp",
    isAccessory: true,
    badgeText: "Ultrasonic Cleaner",
  },
  {
    id: "wadah-soflens-set",
    name: "Wadah Softlens Travel Kit Set",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Sterile Storage", "Includes Tweezers", "Soft Applicator", "Mirror Case"],
    description: "Set wadah perendam softlens higienis lengkap dengan cermin mini, pinset, dan tongkat penjepit steril.",
    price: 15000,
    priceFormatted: "Rp 15.000",
    originalPrice: 22000,
    originalPriceFormatted: "Rp 22.000",
    discountPercentage: "31% OFF",
    image: "/Katalog Soflens/Aksesoris/Wadah Soflens.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Wadah Soflens.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Wadah Soflens.webp",
    isAccessory: true,
    badgeText: "Travel Set",
  },
  {
    id: "wadah-soflens-hijau",
    name: "Wadah Softlens Hijau Mint (Higienis)",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Warna Mint Fresh", "Lengkap Pinset & Botol Mini", "Bebas Bakteri", "Klip Rapat"],
    description: "Travel kit softlens warna hijau mint segar dengan penutup kedap udara dan aplikator lengkap.",
    price: 15000,
    priceFormatted: "Rp 15.000",
    originalPrice: 22000,
    originalPriceFormatted: "Rp 22.000",
    discountPercentage: "31% OFF",
    image: "/Katalog Soflens/Aksesoris/Wadah Soflens Hijau.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Wadah Soflens Hijau.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Wadah Soflens Hijau.webp",
    isAccessory: true,
    badgeText: "Hijau Mint",
  },
  {
    id: "ear-hook",
    name: "Ear Hook Anti-Slip Kacamata",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Silikon Premium", "Anti-Melorot Olahraga", "Sangat Empuk", "Cocok Semua Gagang"],
    description: "Pengait telinga berbahan silikon lembut mencegah kacamata melorot saat berolahraga dan beraktivitas.",
    price: 10000,
    priceFormatted: "Rp 10.000",
    originalPrice: 15000,
    originalPriceFormatted: "Rp 15.000",
    discountPercentage: "33% OFF",
    image: "/Katalog Soflens/Aksesoris/Ear Hook.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Ear Hook.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Ear Hook.webp",
    isAccessory: true,
    badgeText: "Anti-Slip Hook",
  },
  {
    id: "nose-pad-tempel",
    name: "Nose Pad Tempel Silikon Soft",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Silikon Air-Cushion", "Perekat 3M Kuat", "Bebas Bekas di Hidung", "Anti-Sakit"],
    description: "Bantalan hidung silikon fleksibel menambah kenyamanan & mencegah kacamata melorot atau meninggalkan bekas.",
    price: 12000,
    priceFormatted: "Rp 12.000",
    originalPrice: 18000,
    originalPriceFormatted: "Rp 18.000",
    discountPercentage: "33% OFF",
    image: "/Katalog Soflens/Aksesoris/Nose pad Tempel.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Nose pad Tempel.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Nose pad Tempel.webp",
    isAccessory: true,
    badgeText: "Nosepad Cushion",
  },
  {
    id: "strap-kacamata",
    name: "Strap Tali Kacamata Sport / Etnik",
    category: "Aksesoris & Perawatan",
    colorFamily: "accessory",
    specs: ["Tali Flexible Adjustable", "Pengunci Karet Kuat", "Trendy & Modis", "Mencegah Kacamata Jatuh"],
    description: "Tali gantungan kacamata stylish & kuat menjaga kacamata tetap aman di leher saat tidak dipakai.",
    price: 15000,
    priceFormatted: "Rp 15.000",
    originalPrice: 25000,
    originalPriceFormatted: "Rp 25.000",
    discountPercentage: "40% OFF",
    image: "/Katalog Soflens/Aksesoris/Strap Kacamata.webp",
    hoverImage: "/Katalog Soflens/Aksesoris/Strap Kacamata.webp",
    detailPoster: "/Katalog Soflens/Aksesoris/Strap Kacamata.webp",
    isAccessory: true,
    badgeText: "Strap Kacamata",
  },
];

export const SOFTLENS_FAQ = [
  {
    id: "minus-tinggi",
    icon: "👁️",
    title: "Minus Tinggi & Resep Presisi",
    desc: "Ready stok softlens dari normal (plano) hingga minus tinggi -10.00! Tim CS kami siap mencocokkan resep mata kamu.",
  },
  {
    id: "silinder",
    icon: "🔄",
    title: "Silinder (Astigmatism)",
    desc: "Tersedia pemesanan softlens khusus silinder/astigmatism dengan Axis presisi tinggi demi kenyamanan fokus.",
  },
  {
    id: "cara-pakai",
    icon: "🤲",
    title: "Cara Pakai & Higienitas",
    desc: "Selalu cuci tangan bersih dengan sabun, dan rendam softlens minimal 4 jam sebelum pemakaian awal.",
  },
  {
    id: "cairan-oksi",
    icon: "🧴",
    title: "Cairan Pembersih Steril",
    desc: "Gunakan cairan pembersih khusus (ICE / X2 / Pure N'Soft) untuk melepaskan endapan protein pada permukaan lensa.",
  },
  {
    id: "tetes-mata",
    icon: "💧",
    title: "Tetes Mata Pelembab",
    desc: "Gunakan tetes X2 Contacts saat mata terasa kering di ruangan ber-AC untuk menjaga kelembaban sepanjang hari.",
  },
  {
    id: "aksesoris-set",
    icon: "🧰",
    title: "Perawatan Lens Case",
    desc: "Ganti wadah perendam softlens secara berkala 1-2 bulan sekali demi menjaga kesehatan & kesegaran mata.",
  },
];
