export type Testimonial = {
  id: string;
  name: string;
  avatar?: string;
  rating: number;
  date: string;
  text: string;
  branch: "Purwokerto" | "Purbalingga" | "Wonosobo" | "Cilacap";
  source: "google";
  badge?: string; // e.g. "Local Guide"
};

export const TESTIMONIALS: Testimonial[] = [
  // ── PURWOKERTO (Review Asli Google Maps) ──────────────────────────────────
  {
    id: "rev-pwt-1",
    name: "Yoko Fikri",
    rating: 5,
    date: "5 bulan lalu",
    text: "Pertama kali ke sini, pelayanan ramah, dijelaskan secara detail jenis dan harganya. Bahkan ketika mau bayar, kasir mengingatkan lg apakah udah yakin dengan jenis frame yg dipilih.. Sayang aja gak sekalian pilih yg night drive kemaren.",
    branch: "Purwokerto",
    source: "google",
  },
  {
    id: "rev-pwt-2",
    name: "Puput Avrianti",
    rating: 5,
    date: "setahun lalu",
    text: "Pertama kali mampir ke iseeyou purwokerto, ternyata frame nya murah-murah banget, model nya juga update bgt terbaru semua, harga terjangkau staff ramah.",
    branch: "Purwokerto",
    source: "google",
  },
  {
    id: "rev-pwt-3",
    name: "dayu pengukir02",
    rating: 5,
    date: "7 bulan lalu",
    text: "Pelayannya bagus poll, tempatnya estetik dan pilihan frame nya banyak sekali.",
    branch: "Purwokerto",
    source: "google",
  },
  {
    id: "rev-pwt-4",
    name: "hafidzah laila",
    rating: 5,
    date: "setahun lalu",
    text: "Pegawai nya ramah baik bgt + sabar bantuin satu satu nyari frameku yg cocok, tempat nyaman dan adem, modelnya cantik cantik semua.",
    branch: "Purwokerto",
    source: "google",
  },
  {
    id: "rev-pwt-5",
    name: "Adya Raras Pramesti",
    rating: 5,
    date: "7 bulan lalu",
    text: "Pelayanannya sangat membantu dan ramah-ramah, kacamatanya keluaran terbaru, dan tempatnya nyaman.",
    branch: "Purwokerto",
    source: "google",
  },
  {
    id: "rev-pwt-6",
    name: "Rifaul Ch",
    rating: 5,
    date: "setahun lalu",
    text: "Rekomen banget sekarang i see you tempatnya makin besar, pelayanannya juga semakin meningkat.",
    branch: "Purwokerto",
    source: "google",
  },
  {
    id: "rev-pwt-7",
    name: "Nurul Anggraeni",
    rating: 5,
    date: "8 bulan lalu",
    text: "Pelayanannya sangat bagus dan sangat gercep, Untuk varian frame banyak jenisnya dan worth it bgtt harganya.",
    branch: "Purwokerto",
    source: "google",
  },
  {
    id: "rev-pwt-8",
    name: "Riana riez",
    rating: 5,
    date: "7 bulan lalu",
    badge: "Local Guide",
    text: "Good service. Tempat luas, banyak pilihan frame, tempat tunggu juga nyaman. Disediakan air minum bagi pengunjung. Harga juga affordable. Area pwt yg mau cari glasses bole merapat.",
    branch: "Purwokerto",
    source: "google",
  },
  {
    id: "rev-pwt-9",
    name: "sikwi puspita",
    rating: 5,
    date: "7 bulan lalu",
    text: "Optik terlengkap dan termurah yang pernah sy temui. Harga rasa online tapi kualitas oke banget. Udah 2 kali ganti kacamata, tetep i see you pilihanku, rela jauh-jauh dari banyumas.",
    branch: "Purwokerto",
    source: "google",
  },
  {
    id: "rev-pwt-10",
    name: "Nur Hasanah",
    rating: 5,
    date: "7 bulan lalu",
    text: "Tempatnya nyaman, pelayanan ramah, banyak pilihan frame sampai bingung mau pilih yang mana hehe. Parkiran luas, cek mata juga gratis, udah langganan dari 2021.",
    branch: "Purwokerto",
    source: "google",
  },
  {
    id: "rev-pwt-11",
    name: "Adinda Nur A",
    rating: 4,
    date: "5 bulan lalu",
    text: "Framenya pilihannya banyak sekaliii, sukakk! Kaka kasir kemarin karena hectic dan ramai mungkin jadi lupa menyampaikan perihal diskon, tapi kaka admin komplain lumayan komunikatif dan memberikan feedback dengan baik.",
    branch: "Purwokerto",
    source: "google",
  },
  {
    id: "rev-pwt-12",
    name: "Afrilia SN",
    rating: 5,
    date: "7 bulan lalu",
    text: "Gilakk si ini toko kacamata lengkap bgt kalo mau nyari frame, softlens dll best pokoknya i see you.",
    branch: "Purwokerto",
    source: "google",
  },
  {
    id: "rev-pwt-13",
    name: "Angelina Agmay",
    rating: 5,
    date: "8 bulan lalu",
    text: "Toko kacamata yang gen z bangett! Tokonya ramai tapi pelayanannya cepat. Tempat tunggunya cozy banget.",
    branch: "Purwokerto",
    source: "google",
  },

  // ── PURBALINGGA (Review Asli Google Maps) ─────────────────────────────────
  {
    id: "rev-pbg-1",
    name: "sasaa",
    rating: 5,
    date: "4 bulan lalu",
    badge: "Local Guide",
    text: "Akuu abis kesini sama mamaa, disini tuh tempatnya bersih trs pilihan framenya banyak apa lagi kasirnya ramah sama harganya juga terjangkau. Disini jg bisa sekalian cek mata trs waktu abis dicek yang jelasin tuh enak dipahami.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-2",
    name: "Apik Maulidah Purnaningsih",
    rating: 5,
    date: "4 bulan lalu",
    badge: "Local Guide",
    text: "Dilayani dengaan baik, tempatnya bersih, parkir cukup luas, variasi frame banyak, harga cukup terjangkau.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-3",
    name: "misti yanti",
    rating: 5,
    date: "2 bulan lalu",
    text: "Tempat nyaman, pilihan frame banyak, bisa ditunggu untuk penggantian lensa kacamatanya, bisa cek minus dan plus, staff ramah.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-4",
    name: "Rizna Mariska",
    rating: 5,
    date: "7 bulan lalu",
    text: "Rekomen untuk cari kacamata di I see youu, tempat bagus, bersih pelayanan nya ramah. Sukses selalu i see you semoga bisa buka cabang dimana mana.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-5",
    name: "Eka F K",
    rating: 5,
    date: "3 bulan lalu",
    badge: "Local Guide",
    text: "Proses cepat, pelayanan ramah. Pembelian ke 2 di Optik I See You, selalu puas sama pelayanannya, frame yang beragam dengan harga terjangkau.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-6",
    name: "Amalia Diniati Safi",
    rating: 5,
    date: "6 bulan lalu",
    text: "Pelayanannya keren, prosesnya cepet, & penjelasannya bagus. Thee bessttt.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-7",
    name: "MA'BEST MUFFLER",
    rating: 5,
    date: "5 bulan lalu",
    text: "Pelayanannya memuaskan bagus apalagi yang namanya kak lulu kerjanya profesional rekomended bgt buat kalian yang mau periksa mata atau ganti kacamata gaskeenn.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-8",
    name: "Imel Andriyani",
    rating: 5,
    date: "5 bulan lalu",
    text: "Tempatnya bersih nyaman, tersedia berbagai frame yang bagus, pelayanannya ramah ramah, dan memberikan penjelasan yang mudah dipahami.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-9",
    name: "Putri Ayu PN",
    rating: 5,
    date: "7 bulan lalu",
    text: "Pelayanan ramah, model banyak bisa pilih sendiri jadi ngga ribet.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-10",
    name: "Fitri Sundari",
    rating: 5,
    date: "4 minggu lalu",
    text: "Pilihan frame banyak dan bagus rekomen deh pokoknya.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-11",
    name: "Syifa Annisa",
    rating: 5,
    date: "5 bulan lalu",
    text: "Pelayanan ramah, tempatnyaa bagus dan bersih.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-12",
    name: "Prisca Auliyabanafsah",
    rating: 5,
    date: "4 bulan lalu",
    text: "Tempatnya bersih rapi nyaman, pelayanannya juga best banget sii, thank u i see u.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-13",
    name: "lely erawati",
    rating: 5,
    date: "4 bulan lalu",
    text: "Pelayanan ramah, bagus, produk banyak pilihan dan kekinian, harga terjangkau. Recomendit bgt buat sayangi matamu.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-14",
    name: "Lusi ana Palupi",
    rating: 5,
    date: "3 bulan lalu",
    text: "Lengkap sekali, ramah dan memang terbaik dulu harus ke purwokerto sekarang gak perlu jauh-jauh lagii.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-15",
    name: "itsmeanyaa",
    rating: 5,
    date: "4 bulan lalu",
    text: "Tempatnya nyaman, bersih, pelayanannya okee, banyak variasi kacamatanya. Recomended bgt siii, terjangkau jugaaa harganyaa.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-16",
    name: "Utami Putri",
    rating: 5,
    date: "4 bulan lalu",
    text: "Pelayanannya ramah. Tempat nyamann.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-17",
    name: "Afi Nazlia",
    rating: 5,
    date: "4 bulan lalu",
    text: "Tempat nyaman, variasi framenya banyak, pelayanannya ramah & harganya terjangkau.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-18",
    name: "Garam Asam",
    rating: 5,
    date: "5 bulan lalu",
    text: "Mantap 4 kali ke sini, cuma sekarang ada penyesuaian harga. Wajar tapi kualitas tetap oke banget.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-19",
    name: "Fia Nur Ikhdya",
    rating: 5,
    date: "2 bulan lalu",
    text: "Tempatnya cozy nyaman pilihan kacamatanya banyak dan petugasnya sangat ramah sekali.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-20",
    name: "Dini Antika",
    rating: 5,
    date: "8 bulan lalu",
    text: "Pelayanan ramah, tempatnya nyaman banyak pilihan frame.. Rekomend banget.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-21",
    name: "Tias Puspita",
    rating: 5,
    date: "10 bulan lalu",
    badge: "Local Guide",
    text: "Pelayanan ramah banget. Model frame kekinian dan banyak pilihan. Tempatnya jg nyaman. Sukses terus i see u purbalingga.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-22",
    name: "narennaqa",
    rating: 5,
    date: "8 bulan lalu",
    text: "Tempatnya nyaman, pelayanan ramah, harga Ok.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-23",
    name: "Wahyuni",
    rating: 5,
    date: "sebulan lalu",
    text: "Bagus pelayanannya ramah..",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-24",
    name: "Isnaeni Mutmainah",
    rating: 5,
    date: "4 bulan lalu",
    text: "Tempatnya nyaman dan bersih, pelayanan ramah dan harganya affordable.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-25",
    name: "Azkiyatun Nurlailiyah",
    rating: 5,
    date: "5 bulan lalu",
    text: "Setiap ke i see you selalu dapet promo. Tempat oke, pelayanan juga oke, banyak pilihan frame kekinian juga. I love i see you.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-26",
    name: "warieh koesoema",
    rating: 5,
    date: "6 bulan lalu",
    text: "Tempatnya nyaman, pelayanan ramah sekali... after salesnya jg bagus...",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-27",
    name: "Intan Aprilia",
    rating: 5,
    date: "sebulan lalu",
    text: "Disini tempatnya bersih trs pilihan framenya banyak apa lagi kasirnya ramah sama harganya juga terjangkau. Pengecekan matanya juga bagus dan cepettt, sip banget pokoknyaa.",
    branch: "Purbalingga",
    source: "google",
  },
  {
    id: "rev-pbg-28",
    name: "Laela Anggraeni",
    rating: 5,
    date: "sebulan lalu",
    text: "Pelayanan ramah, tempat juga nyaman, banyak pilihan framenya, harga terjangkau.. Mantul pokoknya.",
    branch: "Purbalingga",
    source: "google",
  },

  // ── WONOSOBO (Review Asli Google Maps) ───────────────────────────────────
  {
    id: "rev-wns-1",
    name: "Tika Yulistiana",
    rating: 5,
    date: "8 bulan lalu",
    text: "tempatnya sangat nyamann pelayanan ramahhh sangat rekomended buat yang cari kacamata yang lagi trendi di wonosobo",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-2",
    name: "Fatma sari Ramadhani",
    rating: 5,
    date: "11 bulan lalu",
    badge: "Local Guide",
    text: "optik ternyaman, pelayanan ramah, yg bingung cari kacamata nanti bisa dibantu sama staff disini. pelayanan juga cepet cuma 20menitan udah bisa pake kacamata baruuu. dpt diskon jadi harga masih terjangkau, terimakasih!",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-3",
    name: "Ovi Anti",
    rating: 5,
    date: "8 bulan lalu",
    text: "optik ternyaman, pelayanan ramah, yg bingung cari kacamata nanti bisa dibantu sama staff disini. pelayanan juga cepet cuma 20menitan udah bisa pake kacamata baruuu. dpt diskon jadi harga masih terjangkau, terimakasih!",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-4",
    name: "zuhra zustia pramudhiana",
    rating: 5,
    date: "7 bulan lalu",
    text: "Pelayanan ramah, dan membantu banget, bintang 5 ! Model nya lucuu lucuu bgt, rekomendeddd.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-5",
    name: "Sofi Ainun Firdany",
    rating: 5,
    date: "6 bulan lalu",
    text: "Pelayanan baik, ramah, model lengkap dan bagus bagus, tempatnya nyaman.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-6",
    name: "Hanif Dwi Hatmoko",
    rating: 5,
    date: "5 bulan lalu",
    text: "Rekomendasi banget buat teman teman yang mau cari frame dan lensa kacamata, pilihannya banyak banget dan produknya wow banget yuk boleh mampir ke i see you wonosobo",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-7",
    name: "Leni Wulandari",
    rating: 5,
    date: "setahun lalu",
    text: "Recomended staff ramah banyak pilihan frame dan lensa 100/10",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-8",
    name: "Jannatan Firdaus",
    rating: 5,
    date: "setahun lalu",
    text: "Pelayanannya ramah banget dan cepet juga prosesnya meski nambah minusnya wkw tapi oke banget sih recomended optik teramah di wonosobo",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-9",
    name: "fefi isnani",
    rating: 5,
    date: "7 bulan lalu",
    text: "Rekomend toko kacamata di wonosobo, pelayanannya ramahh bgtt bintang 5, banyk varian frame kacamata kekinian dan aesthetic, harga worth it bgt, kalian yang lagi cari kacamata wajib datengin ke toko ini di wonosobo.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-10",
    name: "Widya Dwi Rahayu",
    rating: 5,
    date: "11 bulan lalu",
    text: "Pelayanannya ok banget, pilihan framenya juga banyak.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-11",
    name: "Snow Snowpie",
    rating: 5,
    date: "11 bulan lalu",
    text: "Tempatnya nyaman framenya bisa dicoba semua di display, instagramable juga, pelayanannya cepat dan ramah.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-12",
    name: "033 Kania Dwi",
    rating: 5,
    date: "3 bulan lalu",
    text: "recommended bgt dan kakak nya ramah, nyaman pula tempatnya.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-13",
    name: "hanida desira",
    rating: 5,
    date: "5 bulan lalu",
    text: "Pelayanan ramah harga terjangkau.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-14",
    name: "Citranty Faustin",
    rating: 5,
    date: "8 bulan lalu",
    text: "sangat recommended, staff nya ramah, tokonya juga bersihh wangii, kakak2nya cantik cantik sabarr juga milihin frame nyaa, terimakasih banyakk i see you.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-15",
    name: "Nadia Prastikawati",
    rating: 5,
    date: "11 bulan lalu",
    text: "Pelayanan sangat ramah, harga terjangkau, pembayaran mudah.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-16",
    name: "dwita hayu",
    rating: 5,
    date: "9 bulan lalu",
    text: "pelayanan super baik, cepat, ramah.. good semuanyaaa!!",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-17",
    name: "Najwa Sabilla",
    rating: 5,
    date: "9 bulan lalu",
    text: "Pelayanan ramah, harga effordable, tempatnya nyaman, dibantu dalam pengecekan mata sekaligus pengecekan lensa kacamata sebelumnya.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-18",
    name: "RACHEL PASA VICHA ABDILLA",
    rating: 5,
    date: "8 bulan lalu",
    text: "Pelayanan ramah, pilihan frame dan lensa macam macam, mb mas nya sabar milihin lensa yg pas buat aku.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-19",
    name: "Alvi Nurin Najmi",
    rating: 5,
    date: "8 bulan lalu",
    badge: "Local Guide",
    text: "Pelayanan ramah bintang 5, pelayanan oke dan diarahkan serta di jelaskan secara detail. sangat di rekomendasikan untuk toko Kacamata area Wonosobo.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-20",
    name: "Yuliana",
    rating: 5,
    date: "11 bulan lalu",
    text: "Bagus bgt pelayanannya .. murah-murah.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-21",
    name: "snow white",
    rating: 5,
    date: "11 bulan lalu",
    text: "tempatnya nyaman, pelayanannya sangat ramah.",
    branch: "Wonosobo",
    source: "google",
  },
  {
    id: "rev-wns-22",
    name: "Felita Syifa",
    rating: 5,
    date: "11 bulan lalu",
    text: "Optik i see you Wonosobo pilihan frame nyaa bagus + cantik-cantik, pelayanannya juga oke banget ramah, gercep. Harganyaa super worth it ramah di kantong hiihihi.. Rekomend sii beli kacamata disini.",
    branch: "Wonosobo",
    source: "google",
  },

  // ── CILACAP (Review Asli Google Maps) ─────────────────────────────────────
  {
    id: "rev-clp-1",
    name: "Putri Nurrizkya",
    rating: 5,
    date: "5 bulan lalu",
    text: "pelayanan nya oke, staff nya ramah, pelayanannya cepat dan tanggap terbaik i see you. kebetulan beli pas periode dapet thr.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-2",
    name: "Nangsit Benoa",
    rating: 5,
    date: "4 minggu lalu",
    text: "Udah 2 kali beli dsni alhamdulillah cocok dilayani dgn ramah bestt i see you suka frame nya trendy.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-3",
    name: "Barkah Ade Kurnia",
    rating: 5,
    date: "7 bulan lalu",
    badge: "Local Guide",
    text: "Langganan beli kacamata disini, harganya terjangkau dan banyak pilihan frame yang bagus bagus buat cowo maupun cewe. Dapet garansi 1x perbaikan/penyesuaian apabila di rasa tidak cocok... Recomended sihh.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-4",
    name: "Esa Elftodie",
    rating: 5,
    date: "3 bulan lalu",
    text: "Selalu rekomen i see you ke siapa pun karena senyaman itu tempat dan pelayanannya. Kacamatanya juga bagus-bagus, buat anak-anak sampai orangtua. Harga juga affordable banget. Pembelian udah 4 kali ini di sini.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-5",
    name: "Nathania Ramadhani",
    rating: 5,
    date: "5 bulan lalu",
    text: "Pelayanan di toko ini sangat baik, staff-nya ramah dan membantu saat memilih frame. Proses cek mata juga dijelaskan dengan jelas, jadi lebih paham kondisi mata sendiri. Pilihan model kacamata banyak dan harganya masih reasonable.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-6",
    name: "Nia Gamol",
    rating: 5,
    date: "4 minggu lalu",
    text: "Tempat nya nyaman bisa di tunggu kacamata sya langsung jadi. Stafnya jg ramah.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-7",
    name: "ponyo",
    rating: 5,
    date: "setahun lalu",
    badge: "Local Guide",
    text: "Pelayanan sangat ramah, banyak promo.. karyawan nya sangat informatif.. tempat sejuk dan bersih.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-8",
    name: "devanda rafly ardiansyah",
    rating: 5,
    date: "8 bulan lalu",
    text: "Pelayanan sangat bagus, rekomendasi bgt buat yg mau cek mata dan beli kacamata nya.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-9",
    name: "Lina Anggraeni",
    rating: 5,
    date: "5 bulan lalu",
    text: "Pelayanan over all bagus ramah, model juga bagus bagus... Di pertahankan ya kaka.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-10",
    name: "Iuroh Faa",
    rating: 5,
    date: "setahun lalu",
    text: "Tempatnya nyaman, pelayanan ramah, frame nya bagus-bagus dah 2x selalu ke i see you.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-11",
    name: "RIFA - Siti Rif'atus Sa'adah",
    rating: 5,
    date: "setahun lalu",
    badge: "Local Guide",
    text: "Pembuatan kacamata baru stelah sekian tahun nggak bikin kacamata. Tempat nya adem, pegawainya ramah, harga affordable banget.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-12",
    name: "sandra cahyaningtyas",
    rating: 5,
    date: "setahun lalu",
    text: "Pelayanan sangat ramah dan cepat selesai.... framenya juga bagus-bagus.. Selalu langganan dari Purwokerto sampe sekarang udah buka di cilacap.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-13",
    name: "Yossy Yuliyatin",
    rating: 5,
    date: "7 bulan lalu",
    badge: "Local Guide",
    text: "Tempat nya nyaman, ramah banget suka banget.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-14",
    name: "Youla Marlinda Putri",
    rating: 5,
    date: "setahun lalu",
    text: "barangnya bagus banget pelayanannya ramah dan harganya cukup terjangkau.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-15",
    name: "Fatma Wati",
    rating: 5,
    date: "5 bulan lalu",
    text: "Pelayanan baikk ramah.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-16",
    name: "Bima Ghafaro",
    rating: 5,
    date: "7 bulan lalu",
    text: "bagus banyak pilihan, lengkap ada diskon juga.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-17",
    name: "Ikhsan Fajar Kurnia",
    rating: 5,
    date: "setahun lalu",
    text: "Pelayanan yang sangat bagus, staffnya ramah.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-18",
    name: "Putri Allawiyah",
    rating: 5,
    date: "8 bulan lalu",
    text: "Pelayannya bintang 5, mba mas nya ramah poll, terus bisa minta rekomendasi kacamata yang cocok sama kita, aku rekomen banget buat kalian kesini.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-19",
    name: "Utami Tia",
    rating: 5,
    date: "setahun lalu",
    badge: "Local Guide",
    text: "Pelayanan bagus, tempat nyaman, harga murah.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-20",
    name: "Alfi Nur Azmi",
    rating: 5,
    date: "setahun lalu",
    text: "Pelayanan sangat bagus, rekomendasi bgt buat yg mau cek mata dan beli kacamata nya.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-21",
    name: "Ama Lia",
    rating: 5,
    date: "setahun lalu",
    text: "Pilihan bervariasi, harga terjangkau, pelayanan ramah, gercep dan kerennn... kacamata juga jadinya cepet.. salutt i see you optic cilacap..",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-22",
    name: "Savira Nur fitriani",
    rating: 5,
    date: "setahun lalu",
    text: "Tempatnya sangat nyaman.. pelayanan juga bagus banget, banyak promonya.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-23",
    name: "Nila Anggunpriyadi",
    rating: 5,
    date: "setahun lalu",
    text: "pelayanan ramah, tempat nyaman.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-24",
    name: "fresiskadr dr",
    rating: 5,
    date: "8 bulan lalu",
    text: "Pelayanan nyaman, pengecekan nyaman. Banyak frame lucu dan keren.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-25",
    name: "Ndr Collection",
    rating: 5,
    date: "8 bulan lalu",
    badge: "Local Guide",
    text: "Aku udah bikin kacamata 2X di Isee you. Pertama waktu ada event bareng paragraf coffe. Trus kedua bikin kemarin puasa. Menurut aku tuh disini worth it, banyak pilihan frame yg kekinian + murah. Modelnya selalu update.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-26",
    name: "Intan Rosendas",
    rating: 5,
    date: "setahun lalu",
    text: "pelayanannya ramah, banyak pilihan frame nya jugaaa.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-27",
    name: "Arif Ardhani",
    rating: 5,
    date: "setahun lalu",
    text: "Pelayanan ramah, periksa matanya gratis dan masih ada promonya, model framenya banyak farian.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-28",
    name: "hana alam",
    rating: 5,
    date: "6 bulan lalu",
    text: "Pelayanan ramah, tempat bersih dan banyak pilihan frame nya.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-29",
    name: "Tiara 12",
    rating: 5,
    date: "setahun lalu",
    text: "Pelayanan ramah sekali top bgtt modelnya bagus.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-30",
    name: "Syifa Nur Baeti",
    rating: 5,
    date: "8 bulan lalu",
    text: "Pelayanannya sat set cepet bangett.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-31",
    name: "Zhi Leztha",
    rating: 5,
    date: "setahun lalu",
    text: "Pelayanannya sangat baguss.....dan memuaskan.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-32",
    name: "Siti Nur aini",
    rating: 5,
    date: "7 bulan lalu",
    text: "pelayanan sangat memuaskan yaa, pilihan frame jugaa banyakk, recommend banget.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-33",
    name: "Ahmad Sholehudin",
    rating: 5,
    date: "setahun lalu",
    text: "Bagus pelayanan, murah kualitas bagus.",
    branch: "Cilacap",
    source: "google",
  },
  {
    id: "rev-clp-34",
    name: "Ahmad ibrahim Al aziz",
    rating: 5,
    date: "5 bulan lalu",
    text: "pelayanan ramah banget,, bintang 5 pokoknya.",
    branch: "Cilacap",
    source: "google",
  },
];

